### Exploratory Data Analysis (EDA) using NumPy and Pandas

What is EDA?

-> Exploratory Data Analysis (EDA) is the process of understanding, cleaning, analyzing, and visualizing data before applying machine learning or statistical techniques.

EDA using

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("Titanic dataset.csv.csv")

In [4]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500

In [5]:
df.shape

(891, 10)

In [9]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare'],
      dtype='object')

### Dataset Information

In [13]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708

In [14]:
df.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500

In [17]:
df.sample()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000
413,414,0,2,"Cunningham, Mr. Alfred Fleming",male,NaN,0,0,239853,0.0000
411,412,0,3,"Hart, Mr. Henry",male,NaN,0,0,394140,6.8583
272,273,1,2,"Mellinger, Mrs. (Elizabeth Anne Maidment)",female,41.0,0,1,250644,19.5000
742,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,PC 17608,262.3750
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833
293,294,0,3,"Haas, Miss. Aloisia",female,24.0,0,0,349236,8.8500
843,844,0,3,"Lemberopolous, Mr. Peter L",male,34.5,0,0,2683,6.4375
270,271,0,1,"Cairns, Mr. Alexander",male,NaN,0,0,113798,31.0000
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.0,0,2,17421,110.8833
72,73,0,2,"Hood, Mr. Ambrose Jr",male,21.0,0,0,S.O.C. 14879,73.5000
201,202,0,3,"Sage, Mr. Frederick",male,NaN,8,2,CA. 2343,69.5500
127,128,1,3,"Madsen, Mr. Fridtjof Arne",male,24.0,0,0,C 17369,7.1417
657,658,0,3,"Bourke, Mrs. John (Catherine)",female,32.0,1,1,364849,15.5000
457,458,1,1,"Kenyon, Mrs. Frederick R (Marion)",female,NaN,1,0,17464,51.8625
211,212,1,2,"Cameron, Miss. Clear Annie",female,35.0,0,0,F.C.C. 13528,21.0000
241,242,1,3,"Murphy, Miss. Katherine ""Kate""",female,NaN,1,0,367230,15.5000
605,606,0,3,"Lindell, Mr. Edvard Bengtsson",male,36.0,1,0,349910,15.5500
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250
775,776,0,3,"Myhrman, Mr. Pehr Fabian Oliver Malkolm",male,18.0,0,0,347078,7.7500
239,240,0,2,"Hunt, Mr. George Henry",male,33.0,0,0,SCO/W 1585,12.2750

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
dtypes: float64(2), int64(5), object(3)
memory usage: 69.7+ KB

### Checking missing values

In [19]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
dtype: int64

In [20]:
missing_percent =(df.isnull().sum()/len(df))*100
missing_percent.sort_values(ascending=False)

Age            19.86532
PassengerId     0.00000
Survived        0.00000
Pclass          0.00000
Name            0.00000
Sex             0.00000
SibSp           0.00000
Parch           0.00000
Ticket          0.00000
Fare            0.00000
dtype: float64

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
dtype: int64

In [23]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
dtype: object

In [25]:
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [26]:
df[["Age","Fare"]].describe()

              Age        Fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [27]:
Q1 = df["Fare"].quantile(0.25)
Q3 = df["Fare"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[
    (df["Fare"] < lower) |
    (df["Fare"] > upper)
]

len(outliers)

116

### NumPy Statistical Analysis

In [28]:
numeric_cols = ["Age", "Fare"]

In [29]:
np.mean(df["Age"])
np.mean(df["Fare"])

np.float64(32.204207968574636)

In [30]:
np.median(df["Age"].dropna())

np.float64(28.0)

In [31]:
np.median(df["Fare"])

np.float64(14.4542)

In [32]:
np.var(df["Age"].dropna())
np.var(df["Fare"])

2466.6653116850434

In [33]:
np.std(df["Age"].dropna())
np.std(df["Fare"])

49.66553444477411

In [34]:
np.percentile(df["Age"].dropna(), [25,50,75])

array([20.125, 28.   , 38.   ])

In [35]:
np.percentile(df["Fare"], [25,50,75])

array([ 7.9104, 14.4542, 31.    ])

In [36]:
np.min(df["Age"])
np.max(df["Age"])

np.min(df["Fare"])
np.max(df["Fare"])

512.3292

### Univariate Analysis

In [37]:
numeric_cols = df.select_dtypes(include=np.number).columns

print(numeric_cols)

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [38]:
col = "Age"

print("Mean:", np.mean(df[col]))
print("Median:", np.median(df[col].dropna()))
print("Std:", np.std(df[col].dropna()))
print("Min:", np.min(df[col]))
print("Max:", np.max(df[col]))
print("Missing:", df[col].isnull().sum())

Mean: 29.69911764705882
Median: 28.0
Std: 14.516321150817317
Min: 0.42
Max: 80.0
Missing: 177

In [39]:
col = "Fare"

print("Mean:", np.mean(df[col]))
print("Median:", np.median(df[col]))
print("Std:", np.std(df[col]))
print("Min:", np.min(df[col]))
print("Max:", np.max(df[col]))

Mean: 32.204207968574636
Median: 14.4542
Std: 49.66553444477411
Min: 0.0
Max: 512.3292

In [40]:
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [41]:
(df["Sex"].value_counts(normalize=True)*100).round(2)

Sex
male      64.76
female    35.24
Name: proportion, dtype: float64

In [43]:
df["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [44]:
(df["Pclass"].value_counts(normalize=True)*100).round(2)

Pclass
3    55.11
1    24.24
2    20.65
Name: proportion, dtype: float64

In [45]:
pd.crosstab(df["Sex"], df["Survived"])

Survived    0    1
Sex
female     81  233
male      468  109

In [46]:
pd.crosstab(
    df["Sex"],
    df["Survived"],
    normalize="index"
) * 100

Survived          0          1
Sex
female    25.796178  74.203822
male      81.109185  18.890815

In [47]:
pd.crosstab(
    df["Pclass"],
    df["Survived"],
    normalize="index"
) * 100

Survived          0          1
Pclass
1         37.037037  62.962963
2         52.717391  47.282609
3         75.763747  24.236253

### Correlation Analysis

In [50]:
df.corr(numeric_only=True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

In [51]:
df.corr(numeric_only=True)["Survived"]

PassengerId   -0.005007
Survived       1.000000
Pclass        -0.338481
Age           -0.077221
SibSp         -0.035322
Parch          0.081629
Fare           0.257307
Name: Survived, dtype: float64

In [52]:
df["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [53]:
df.groupby("Survived")["Age"].mean()

Survived
0    30.626179
1    28.343690
Name: Age, dtype: float64

In [54]:
df.groupby("Survived")["Fare"].mean()

Survived
0    22.117887
1    48.395408
Name: Fare, dtype: float64

### The survivor had pay more higher fees than non survivor or we can say they are from wealthy family

In [55]:
corr = df.corr(numeric_only=True)
corr["Survived"].sort_values(ascending=False)

Survived       1.000000
Fare           0.257307
Parch          0.081629
PassengerId   -0.005007
SibSp         -0.035322
Age           -0.077221
Pclass        -0.338481
Name: Survived, dtype: float64